Adding support for Vector2f and HapticApply redo
jdonkervliet/openxr-librnr pull request #3
Opened 2024-01-10 21:37 UTC by peg-danielse

sorry for the duplicate pull request somehow my branch got messed up by the formatting changes. If I remember correctly I fixed all the comments.

2024-01-17 13:28 UTC, jdonkervliet requested changes
Other than the missing comments, looks good to me!

2024-01-17 13:28 UTC, jdonkervliet commented on src/layer_shims.cpp
> -    // we don't need all values. especially if there are long periods that noting happens. check if we need to log
Any reason these comments are deleted? If they are outdated, could you replace, not delete? :)

2024-02-13 15:10 UTC, jdonkervliet commented
Can you resolve the conflict, @peg-danielse?

2024-02-14 11:29 UTC, peg-danielse commented
There you go :)

2024-02-27 16:20 UTC, merged